I: 0
L: 16
S: 1
clip: 0
fusion_blocks: midup
guidance_scale: 7.5
inference_config: configs/inference/inference.yaml
invert_video: false
max_length: null
motion_module: pretrained_models/MagicAnimate/temporal_attention/temporal_attention.ckpt
offset: 0
pretrained_appearance_encoder_path: pretrained_models/MagicAnimate/appearance_encoder
pretrained_controlnet_path: pretrained_models/MagicAnimate/densepose_controlnet
pretrained_model_path: pretrained_models/stable-diffusion-v1-5
pretrained_unet_path: ''
pretrained_vae_path: pretrained_models/sd-vae-ft-mse
save_individual_videos: false
savename: ../data/output_videos/input_video7-twomen
seed:
- 1
size: 512
source_image:
- ../data/reference_images/twomen.jpg
steps: 25
video_path:
- ../data/output_videos/input_video7-twomen/densepose_R101.mp4
video_type: condition
